Repository interenship/inctagram, pull requests merged in 2024-09, with the labels that each got.

#14 IN-13 feat: color palette in storybook
  src/shared/ui/colorsPalette.mdx
Labels: documentation

#18 IN-9 feat: add tabs
  package.json
  pnpm-lock.yaml
  src/shared/ui/Tabs/Tabs.stories.tsx
  src/shared/ui/Tabs/Tabs.tsx
  src/shared/ui/Tabs/TabsContent.tsx
  src/shared/ui/Tabs/TabsList.tsx
  src/shared/ui/Tabs/TabsTrigger.tsx
  src/shared/ui/Tabs/index.ts
Labels: enhancement

#24 IN-9 fix: changed the button spelling using Slot
  package.json
  pnpm-lock.yaml
  src/shared/ui/Button/Button.stories.tsx
  src/shared/ui/Button/Button.tsx
Labels: fix

#23 IN-9 refactor: change structure components Tabs
  src/shared/ui/Tabs/Tabs.tsx
  src/shared/ui/Tabs/TabsContent.tsx
  src/shared/ui/Tabs/TabsList.tsx
  src/shared/ui/Tabs/TabsListItem.tsx
  src/shared/ui/Tabs/TabsTrigger.tsx
  src/shared/ui/Tabs/index.ts
Labels: refactor

#31 IN-9 refactor: change place props in components
  src/shared/ui/Tabs/Tabs.tsx
  src/shared/ui/Tabs/TabsListItem.tsx
Labels: refactor

#25 IN-8 feat: add textarea
  src/shared/ui/TextArea/TextArea.stories.tsx
  src/shared/ui/TextArea/TextArea.tsx
  src/shared/ui/TextArea/index.ts
Labels: feat

#28 selectHotFix refactor: change icons import,minor style update
  public/icons/Flag-Russia.tsx
  public/icons/FlagUnitedKingdom.tsx
  src/shared/assets/icons/components/ChevronDown.tsx
  src/shared/assets/icons/components/ChevronUp.tsx
  src/shared/assets/icons/components/FlagRussia.tsx
  src/shared/assets/icons/components/FlagUnitedKingdom.tsx
  src/shared/ui/Select/Select.stories.tsx
  src/shared/ui/Select/Select.tsx
  src/shared/ui/Select/SelectItem.tsx
Labels: refactor

#32 IN-20 feat: add iconography
  src/shared/ui/Iconography/Iconography.mdx
  src/shared/ui/Iconography/iconography.ts
  src/webpack.d.ts
Labels: documentation, feat

#26 IN-3 feat: add Checkbox
  package.json
  pnpm-lock.yaml
  src/shared/ui/Checkbox/Checkbox.stories.tsx
  src/shared/ui/Checkbox/Checkbox.tsx
  src/shared/ui/Checkbox/index.ts
  src/shared/ui/Typography/Typography.stories.tsx
Labels: feat

#37 chore: update pnpm-lock lates version
  pnpm-lock.yaml
Labels: chore

#33 IN-17 feat: Header
  public/icons/Fill bell.svg
  src/shared/assets/icons/components/Bell.tsx
  src/shared/assets/icons/components/FillBell.tsx
  src/shared/ui/Header/Header.stories.tsx
  src/shared/ui/Header/Header.tsx
  src/shared/ui/Header/index.ts
Labels: feat, TODO

#34 IN-19 feat: add ui alerts
  src/shared/assets/icons/components/Close.tsx
  src/shared/ui/Alerts/Alerts.stories.tsx
  src/shared/ui/Alerts/Alerts.tsx
  src/shared/ui/Alerts/index.ts
Labels: feat, TODO

#41 IN-9 fix: change font-weight style
  src/shared/ui/Tabs/TabsListItem.tsx
Labels: fix

#36 IN-22 feat: create Label
  package.json
  pnpm-lock.yaml
  src/shared/ui/Label/Label.stories.tsx
  src/shared/ui/Label/Label.tsx
  src/shared/ui/Label/index.ts
Labels: feat

#42 IN-7 fix: change min width
  src/shared/ui/Button/buttonVariants.ts
Labels: fix

#44 Label fix: fix Label
  src/shared/ui/Label/Label.stories.tsx
  src/shared/ui/Label/Label.tsx
Labels: fix

#35 IN-18 feat: add card
  src/shared/ui/Card/Card.stories.tsx
  src/shared/ui/Card/Card.tsx
  src/shared/ui/Card/index.ts
Labels: feat
