Repository interenship/inctagram, pull requests merged in 2024-10, with the labels that each got.

#49 IN-34 feat: add small select
  src/shared/ui/Select/Select.stories.tsx
  src/shared/ui/Select/Select.tsx
  src/shared/ui/Select/SelectItem.tsx
Labels: feat

#43 IN-21 feat: add sidebar
  src/shared/assets/icons/components/Bookmark.tsx
  src/shared/assets/icons/components/BookmarkOutline.tsx
  src/shared/assets/icons/components/Home.tsx
  src/shared/assets/icons/components/HomeOutline.tsx
  src/shared/assets/icons/components/LogOutOutline.tsx
  src/shared/assets/icons/components/MessageCircle.tsx
  src/shared/assets/icons/components/MessageCircleOutline.tsx
  src/shared/assets/icons/components/Person.tsx
  src/shared/assets/icons/components/PersonOutline.tsx
  src/shared/assets/icons/components/PlusSquare.tsx
  src/shared/assets/icons/components/PlusSquareOutline.tsx
  src/shared/assets/icons/components/SearchOutline.tsx
  src/shared/assets/icons/components/TrendingUp.tsx
  src/shared/assets/icons/components/TrendingUpOutline.tsx
  src/shared/ui/Sidebar/LogOutBtn/LogOutBtn.tsx
  src/shared/ui/Sidebar/LogOutBtn/index.ts
  src/shared/ui/Sidebar/Menu/Menu.tsx
  src/shared/ui/Sidebar/Menu/MenuItem.tsx
  src/shared/ui/Sidebar/Menu/menuData.ts
  src/shared/ui/Sidebar/Sidebar.stories.tsx
  src/shared/ui/Sidebar/Sidebar.tsx
  src/shared/ui/Sidebar/index.ts
  src/shared/ui/Sidebar/types.ts
Labels: feat

#47 Text area fix fix: id can be transmitted externally
  src/shared/ui/TextArea/TextArea.stories.tsx
  src/shared/ui/TextArea/TextArea.tsx
Labels: fix

#40 IN-6 feat: TextField component
  src/shared/assets/icons/components/Close.tsx
  src/shared/assets/icons/components/EyeOffOutline.tsx
  src/shared/assets/icons/components/EyeOutline.tsx
  src/shared/assets/icons/components/Search.tsx
  src/shared/ui/TextField/TextField.stories.tsx
  src/shared/ui/TextField/TextField.tsx
  src/shared/ui/TextField/index.ts
Labels: feat

#45 IN-27 fix: Checkbox
  pnpm-lock.yaml
  src/shared/assets/icons/components/CheckmarkOutline.tsx
  src/shared/ui/Checkbox/Checkbox.stories.tsx
  src/shared/ui/Checkbox/Checkbox.tsx
Labels: fix

#55 Temp branch
  package.json
  pnpm-lock.yaml
  src/pages/api/hello.ts
  src/shared/assets/icons/components/ArrowIosBack.tsx
  src/shared/assets/icons/components/ArrowIosForward.tsx
  src/shared/assets/icons/components/Bookmark.tsx
  src/shared/assets/icons/components/BookmarkOutline.tsx
  src/shared/assets/icons/components/EyeOffOutline.tsx
  src/shared/assets/icons/components/EyeOutline.tsx
  src/shared/assets/icons/components/Home.tsx
  src/shared/assets/icons/components/HomeOutline.tsx
  src/shared/assets/icons/components/LogOutOutline.tsx
  src/shared/assets/icons/components/MessageCircle.tsx
  src/shared/assets/icons/components/MessageCircleOutline.tsx
  src/shared/assets/icons/components/PersonOutline.tsx
  src/shared/assets/icons/components/PlusSquare.tsx
  src/shared/assets/icons/components/PlusSquareOutline.tsx
  src/shared/assets/icons/components/Search.tsx
  src/shared/assets/icons/components/SearchOutline.tsx
  src/shared/assets/icons/components/TrendingUp.tsx
  src/shared/assets/icons/components/TrendingUpOutline.tsx
  src/shared/ui/Alerts/Alerts.stories.tsx
  src/shared/ui/Button/Button.stories.tsx
  src/shared/ui/Card/Card.stories.tsx
  src/shared/ui/Checkbox/Checkbox.stories.tsx
  src/shared/ui/Checkbox/Checkbox.tsx
  src/shared/ui/Header/Header.stories.tsx
  src/shared/ui/Header/Header.tsx
  src/shared/ui/Select/Select.tsx
  src/shared/ui/Select/SelectItem.tsx
  src/shared/ui/TextArea/TextArea.tsx
  src/shared/ui/Typography/Typography.stories.tsx
  tsconfig.json
Labels: fix

#57 expanded global.css
  src/app/styles/globals.css
Labels: chore

#54 smallSelect fix: add ability to change item color
  src/shared/ui/Select/Select.stories.tsx
  src/shared/ui/Select/Select.tsx
Labels: fix

#66 added i18next into project
  next-i18next.config.ts
  package.json
  pnpm-lock.yaml
  src/pages/_app.tsx
  src/shared/resources/en/en.js
  src/shared/resources/index.js
  src/shared/resources/ru/ru.js
Labels: feat
